// Code generated by goro;

package myrepo

// This file was generated by the goro tool.

import (
	"database/sql"

	"github.com/greyfox12/GoDilpom1/internal/adapter/pgsqlxrepo"
)

type Repository struct {
	pgsqlxrepo.Transactor
}

func NewRepository(conn *sql.DB) *Repository {
	return &Repository{
		pgsqlxrepo.NewTransactor(conn),
	}
}
