package app

// This file was generated by the goro tool.
// Editing this file might prove futile when you re-run the goro commands

import (
	"database/sql"

	"github.com/greyfox12/GoDilpom1/internal/config"
	_ "github.com/jackc/pgx/v5/pgconn"
	_ "github.com/jackc/pgx/v5/stdlib"
)

func (a *App) newPgSqlxConnect(cfg config.SQLConfig) (*sql.DB, error) {
	db, err := sql.Open("pgx", cfg.DSN)

	if err != nil {
		return nil, err
	}

	// В текущей реализации не нужно
	//	db.SetConnMaxLifetime(cfg.ConnMaxLifetime)
	//	db.SetMaxOpenConns(cfg.MaxOpenConns)
	//	db.SetMaxIdleConns(cfg.MaxIdleConns)

	return db, err
}
