// Code generated by goro;

package accrualserv

// This file was generated by the goro tool.

import (
	"github.com/greyfox12/GoDilpom1/internal/service"
)

type myRepo interface {
	service.Transactor

	// TODO: define interface to inject a service or an adapter
}

type Service struct {
	myRepo myRepo
}

func NewService(myRepo myRepo) *Service {
	return &Service{

		myRepo: myRepo,
	}
}
